// Export all schemas and types from the schemas directory
export * from './validators';
export * from './api';

// Re-export main types for convenience
export {
    // Base schemas
    BaseModelSchema,
    OrganizationSchema,
    ProfileSchema,
    CourseSchema,
    SectionSchema,
    AssignmentSchema,
    RubricCategorySchema,
    RubricCommentSchema,
    SubmissionSchema,
    FileTemplateSchema,
    FileSchema,
    CommentTagSchema,
    CommentSchema,
    TestCategorySchema,
    TestCaseSchema,
    SubmissionTestSchema,
    SubmissionHistorySchema,
    EnvironmentSchema,
    SolutionFileSchema,
    HelperFileSchema,
    SourceFileSchema,
    UserSchema,
    WebhookSchema,

    // Extended schemas
    AssignmentWithStatisticsSchema,
    CourseWithRosterSchema,
    CourseSettingsSchema,
    CourseRosterSchema,

    // Utility schemas
    CreateAssignmentSchema,
    UpdateAssignmentSchema,
    CreateSubmissionSchema,
    UpdateSubmissionSchema,

    // Types
    Organization,
    Profile,
    Course,
    CourseWithRoster,
    CourseSettings,
    CourseRoster,
    Section,
    Assignment,
    AssignmentWithStatistics,
    RubricCategory,
    RubricComment,
    Submission,
    FileTemplate,
    File,
    CommentTag,
    Comment,
    TestCategory,
    TestCase,
    SubmissionTest,
    SubmissionHistory,
    Environment,
    SolutionFile,
    HelperFile,
    SourceFile,
    User,
    Webhook,
    CreateAssignment,
    UpdateAssignment,
    CreateSubmission,
    UpdateSubmission,
} from '../types';
