import { z } from "zod";

export const FileModelSchema = z.object({
    name: z.string().max(150).describe("The name of the file."),
    code: z.string().describe("The code in a file."),
    submission: z.number().int().describe("The related submission_id."),
    extension: z
        .string()
        .max(36)
        .describe("The extension for the file (e.g. '.java' or '.py')"),
    path: z
        .string()
        .max(500)
        .nullable()
        .optional()
        .describe(
            "Optional file path, delimited by slashes, to indicate a directory structure in submission.",
        ),
    hiddenBeforePublish: z
        .boolean()
        .default(false)
        .describe(
            "Whether this file should hidden to students before their feedback has been published. This is for autogenerated test files that shouldn't be exposed to students on upload.",
        ),
});

export const FileSchema = z.object({
    name: z.string().max(150),
    code: z.string(),
    extension: z.string().max(36),
    submission: z.number().int(),
    id: z.number().int(),
    comments: z.array(z.number()).optional(),
    path: z.string().max(500),
    created: z.any(),
});

export const FileStudentUploadSchema = z.object({
    name: z.string().max(150),
    code: z.string(),
    extension: z.string().max(36),
    submission: z.number().int(),
    id: z.number().int(),
    path: z.string().max(500),
});

export const FileValidationWithoutSubmissionSchema = z.object({
    name: z.string().max(150),
    code: z.string(),
    extension: z.string().max(36),
    path: z.string().max(500).nullable().optional(),
});
