import { z } from "zod";

// Base File schema (without relationships)
const BaseFileSchema = z.object({
    name: z.string().max(250).describe("The name of the file."),
    extension: z.string().max(36).describe("The extension for the file (e.g. '.java' or '.py')"),
    path: z.string().max(500).nullable().optional().describe("Optional file path, delimited by slashes, to indicate a directory structure."),
    created: z.string().optional(),
    modified: z.string().optional(),
    // Support both 'data' (new) and 'code' (legacy) for backwards compatibility
    data: z.string().optional().describe("The data in a file. UTF-8 encoded text."),
    code: z.string().optional().describe("The code in a file (legacy field, use 'data')."),
});

// SubmissionFile schema - files belonging to submissions
export const SubmissionFileModelSchema = BaseFileSchema.extend({
    submission: z.number().int().describe("The related submission_id."),
    hiddenBeforePublish: z
        .boolean()
        .default(false)
        .describe(
            "Whether this file should be hidden to students before their feedback has been published. This is for autogenerated test files that shouldn't be exposed to students on upload."
        ),
    comments: z.array(z.number()).optional(),
    id: z.number().int(),
});

// AssignmentFile schema - files belonging to assignments
export const AssignmentFileModelSchema = BaseFileSchema.extend({
    assignment: z.number().int().describe("The related assignment_id."),
    id: z.number().int(),
});

// CourseFile schema - files belonging to courses
export const CourseFileModelSchema = BaseFileSchema.extend({
    course: z.number().int().describe("The related course_id."),
    id: z.number().int(),
});

// Legacy schemas for backwards compatibility (map to SubmissionFile)
export const FileModelSchema = SubmissionFileModelSchema;

export const FileSchema = z.object({
    name: z.string().max(250),
    data: z.string().optional(),
    code: z.string().optional(),
    extension: z.string().max(36),
    submission: z.number().int(),
    id: z.number().int(),
    comments: z.array(z.number()).optional(),
    path: z.string().max(500).nullable().optional(),
    created: z.string().optional(),
    hiddenBeforePublish: z.boolean().optional(),
});

export const FileStudentUploadSchema = z.object({
    name: z.string().max(250),
    data: z.string().optional(),
    code: z.string().optional(),
    extension: z.string().max(36),
    submission: z.number().int(),
    id: z.number().int(),
    path: z.string().max(500).nullable().optional(),
    hiddenBeforePublish: z.boolean().optional(),
});

export const FileValidationWithoutSubmissionSchema = z.object({
    name: z.string().max(250),
    data: z.string().optional(),
    code: z.string().optional(),
    extension: z.string().max(36),
    path: z.string().max(500).nullable().optional(),
});
